// Handworks/Trades available in Togo
export const handworks = [
    { value: 'carpentry', label: 'Carpentry / Menuiserie' },
    { value: 'plumbing', label: 'Plumbing / Plomberie' },
    { value: 'electrical', label: 'Electrical Work / Électricien' },
    { value: 'painting', label: 'Painting / Peinture' },
    { value: 'masonry', label: 'Masonry / Maçonnerie' },
    { value: 'welding', label: 'Welding / Soudure' },
    { value: 'hairdressing', label: 'Hairdressing / Coiffure' },
    { value: 'tailoring', label: 'Tailoring / Couture' },
    { value: 'mechanics', label: 'Mechanics / Mécanique' },
    { value: 'auto-repair', label: 'Auto Repair / Réparation Auto' },
    { value: 'refrigeration', label: 'Refrigeration / Climatisation' },
    { value: 'tiling', label: 'Tiling / Carrelage' },
    { value: 'landscaping', label: 'Landscaping / Aménagement Paysager' },
    { value: 'construction', label: 'Construction / Construction' },
    { value: 'roofing', label: 'Roofing / Couverture' },
    { value: 'glass-work', label: 'Glass Work / Vitrerie' },
    { value: 'aluminum-work', label: 'Aluminum Work / Menuiserie Alu' },
    { value: 'cleaning', label: 'Cleaning Services / Nettoyage' },
    { value: 'gardening', label: 'Gardening / Jardinage' },
    { value: 'tutoring', label: 'Tutoring / Tutorat' },
    { value: 'web-design', label: 'Web Design / Design Web' },
    { value: 'graphic-design', label: 'Graphic Design / Design Graphique' },
    { value: 'photography', label: 'Photography / Photographie' },
    { value: 'videography', label: 'Videography / Vidéographie' },
    { value: 'translation', label: 'Translation / Traduction' },
    { value: 'writing', label: 'Writing / Rédaction' },
    { value: 'marketing', label: 'Marketing / Marketing' },
    { value: 'consulting', label: 'Consulting / Conseil' },
    { value: 'event-planning', label: 'Event Planning / Organisation d\'événements' },
    { value: 'catering', label: 'Catering / Restauration' },
    { value: 'cooking', label: 'Cooking Services / Services Culinaires' },
    { value: 'fitness', label: 'Fitness Training / Entraînement Physique' },
    { value: 'music', label: 'Music Lessons / Cours de Musique' },
    { value: 'dance', label: 'Dance Lessons / Cours de Danse' },
    { value: 'home-repair', label: 'Home Repair / Réparations à Domicile' },
    { value: 'furniture-repair', label: 'Furniture Repair / Réparation de Meubles' },
    { value: 'upholstery', label: 'Upholstery / Garnissage' },
    { value: 'locksmith', label: 'Locksmith / Serrurier' },
    { value: 'pest-control', label: 'Pest Control / Dératisation' },
    { value: 'leather-work', label: 'Leather Work / Travail du Cuir' },
    { value: 'shoe-repair', label: 'Shoe Repair / Réparation de Chaussures' },
    { value: 'watch-repair', label: 'Watch Repair / Réparation de Montres' },
    { value: 'jewelry', label: 'Jewelry Making / Création de Bijoux' },
    { value: 'other', label: 'Other / Autre' },
];

// Popular locations in Togo
export const togoLocations = [
    { value: 'lome', label: 'Lomé' },
    { value: 'sokode', label: 'Sokodé' },
    { value: 'kara', label: 'Kara' },
    { value: 'atakpame', label: 'Atakpamé' },
    { value: 'tsevia', label: 'Tsévié' },
    { value: 'anecho', label: 'Aného' },
    { value: 'kpalime', label: 'Kpalimé' },
    { value: 'badou', label: 'Badou' },
    { value: 'ganta-ho', label: 'Ganta-Ho' },
    { value: 'dapango', label: 'Dapango' },
    { value: 'vogan', label: 'Vogar' },
    { value: 'tabligbo', label: 'Tabligbo' },
    { value: 'akodeassos', label: 'Akodéassé' },
    { value: 'matcha', label: 'Matcha' },
    { value: 'niamtougou', label: 'Niamtougou' },
    { value: 'sansanne-mango', label: 'Sansanné-Mango' },
    { value: 'dapaong', label: 'Dapaong' },
    { value: 'kandé', label: 'Kandé' },
    { value: 'yendi', label: 'Yendi' },
    { value: 'bafilo', label: 'Bafilo' },
    { value: 'tchamba', label: 'Tchamba' },
    { value: 'sotouboua', label: 'Sotouboua' },
    { value: 'bassar', label: 'Bassar' },
    { value: 'janon', label: 'Janon' },
    { value: 'nokouke', label: 'Nokouke' },
    { value: 'glei', label: 'Gléi' },
    { value: 'dogbo', label: 'Dogbo' },
    { value: 'amlamadamedji', label: 'Amlamé' },
    { value: 'lavie', label: 'Lavié' },
    { value: 'tohoun', label: 'Tohoun' },
    { value: 'agou', label: 'Agou' },
    { value: 'afagnan', label: 'Afagnon' },
    { value: 'ave', label: 'Avé' },
    { value: 'dzita', label: 'Dzita' },
    { value: 'fiave', label: 'Fiavé' },
    { value: 'adeta', label: 'Adéta' },
    { value: 'notse', label: 'Notsé' },
    { value: 'vli', label: 'Vli' },
    { value: 'with-remote', label: 'Remote / À Domicile' },
];
